In [9]:
import pandas as pd
ddata = pd.read_csv('department.csv')
ddata.head()

,S.No.,Display Name,SAM Account Name,Email Address,Department,OU Name
0,1,Tuğçe KUBALAS YILDIRIM,tkubalas,-,Kurumsal İletişim,isten_ayrilanlar/merkez
1,2,Sinan YORGANCIGIL,syorgancigil,-,Pazarlama ve Ticari Strateji,isten_ayrilanlar/merkez
2,3,Gülden DOĞAN,gdogan,-,Satış & Pazarlama / Sales & Marketing,isten_ayrilanlar/merkez
3,4,Sibel YUCEL,syucel,-,Müşteri Hizmetleri / Customer Services,isten_ayrilanlar/fabrika
4,5,Tarık Talha BENLI TELEFON,tbenli-m,-,-,network_access_groups/wifi_connection/users

In [11]:
 ddata = ddata.rename(columns=yeniSutun)
ddata.head()

,S.No.,isim,uname,email,department,oname
0,1,Tuğçe KUBALAS YILDIRIM,tkubalas,-,Kurumsal İletişim,isten_ayrilanlar/merkez
1,2,Sinan YORGANCIGIL,syorgancigil,-,Pazarlama ve Ticari Strateji,isten_ayrilanlar/merkez
2,3,Gülden DOĞAN,gdogan,-,Satış & Pazarlama / Sales & Marketing,isten_ayrilanlar/merkez
3,4,Sibel YUCEL,syucel,-,Müşteri Hizmetleri / Customer Services,isten_ayrilanlar/fabrika
4,5,Tarık Talha BENLI TELEFON,tbenli-m,-,-,network_access_groups/wifi_connection/users

In [16]:
ddata["oname"].unique()

<ArrowStringArray>
[                                                                                          'isten_ayrilanlar/merkez',
                                                                                          'isten_ayrilanlar/fabrika',
                                                                       'network_access_groups/wifi_connection/users',
                                                                                     'servers/fabrika_servers/users',
                                                                                         'isten_ayrilanlar/danisman',
                                                                          'devices/fabrika_otomasyon/boyahane/users',
                                                                                    'isten_ayrilanlar/yurtdisi_ofis',
                                                                                                    'danisman_users',
                                                                                                     'tableau/users',
                                                                                                        'mail_users',
 ...
                                                               'office/fabrika/uretim_planlama/elyaf_ambar/services',
              'office/fabrika/operasyon_direktorlugu/kalite_guvence_musteri_teknik_hizmetleri/renk_kontrol/services',
                                      'office/fabrika/satis_pazarlama_direktorlugu/urun_mudurlugu/dar _dokuma/users',
                                                                'devices/sürekli_acik_cihazlar/satis_magazasi/users',
 'office/fabrika/operasyon_direktorlugu/makine_enerji/makine_gelistirme_yardimci_isletmeler/makine_gelistirme/users',
                     'office/fabrika/operasyon_direktorlugu/kalite_guvence_musteri_teknik_hizmetleri/yonetici/users',
                                                                     'office/fabrika/uretim_planlama/yonetici/users',
                                                                     'office/fabrika/teknik_mudurluk/yonetici/users',
                                             'office/fabrika/operasyon_direktorlugu/boyahane/yumusak_bobin/services',
                                                      'office/fabrika/operasyon_direktorlugu/iplik/straygharn/users']
Length: 179, dtype: str

In [17]:
silinecek_oular = [
    "isten_ayrilanlar/merkez",
    "isten_ayrilanlar/fabrika",
    "isten_ayrilanlar/uretim",
    "isten_ayrilanlar/danisman",
]

ddata.drop(ddata[ddata["oname"].isin(silinecek_oular)].index, inplace=True)

In [18]:
ddata["department"].unique()

<ArrowStringArray>
[                                                       '-',
                                                    'Sales',
                                      'Bilgi Teknolojileri',
                                                 'Boyahane',
                                                    'Ar-Ge',
                                       'Ar-Ge ve İnovasyon',
                                                  'Garment',
                                         'Insan Kaynaklari',
                                                    'Bakim',
                                             'Cozgu Dokuma',
                   'Müşteri Hizmetleri / Customer Services',
                              'Çözgü ve Dokuma İşletmeleri',
                                         'İnsan Kaynakları',
                 'Makine Geliştirme ve Yardımcı İşletmeler',
                                       'Maliyet Muhasebesi',
                                                    'Satış',
                                        'İplik İşletmeleri',
                                         'Apre İşletmeleri',
                                       'Ticaret Muhasebesi',
                                          'Üretim Planlama',
              'Kalite Güvence ve Müşteri Teknik Hizmetleri',
                                  'Mali İşler Direktörlüğü',
             'Operasyonel Mükemmellik ve Sistem Geliştirme',
                                               'İç Denetim',
                                             'Makine Bakım',
                        'Finansman ve Yatırımcı İlişkileri',
                                         'Boya İşletmeleri',
                                                   'Finans',
                                                    'Iplik',
                                              'Hazır Giyim',
               'İnsan Kaynakları ve Organizasyonel Gelişim',
                                       'Ürün Kodu Yönetimi',
                                       'Bütçe ve Raporlama',
                                 'Satınalma ve Dış Ticaret',
                  'Kalite Guvence Musteri Teknik Hizmetler',
                  'Ar-Ge ve İnovasyon / R&D and Innovation',
                                    'Tasarım ve Koleksiyon',
                                                     'Apre',
                                        'Kurumsal İletişim',
                                 'İplik ve Fason Satınalma',
                                                'Satınalma',
                             'Elektrik ve Elektronik Bakım',
                                                    'İplik',
                          'İş Güvenliği, Çevre ve Kimyasal',
                          'Mamül Geliştirme ve İyileştirme',
                                              'İplik Ambar',
                                                    'Hukuk',
                                         'İthalatOperasyon',
                               'Boya ve Kimyasal Otomasyon',
                   'İplik Proses Geliştirme ve İyileştirme',
                                          'Numune Planlama',
                                'Elektrik Elektronik Bakım',
                                              'İdari İşler',
           'Apre Proses ve Mamul Geliştirme ve İyileştirme',
                                                 'Ambarlar',
                                'Satış Analiz ve Raporlama',
  'Satış ve Müşteri Hizmetleri / Sales & Customer Services',
                                               'İş Sağlığı',
                  'Endüstriyel Ürünler ve Hizmet Satınalma',
                                            'Satış / Sales',
                                   'Operasyon Direktörlüğü',
                  'Makine Geliştirme & Yardımcı İşletmeler',
                                               'Kumaş Boya',
                                          'Teknik Müdürlük',
                                  'Dış Ticaret ve Lojistik',
                                     'Satınalma Muhasebesi',
                                       'Hammadde Satınalma',
                                          'İş Mükemmelliği',
                                        'İhracat Operasyon',
                      'Genel Müdürlük / General Management',
                                           'Genel Müdürlük',
                               'Ürün Geliştirme ve Tasarım',
 'Satınalma ve Dış Ticaret / Procurement and Foreign Trade',
                                                 'Muhasebe',
                                    'İş Güvenliği ve Çevre',
                                       'Kimya Laboratuvarı',
                                       'Pazarlama ve Satış',
                                          'Tedarik Zinciri',
                                                  'Kartela',
                        'Satış ve Tasarım / Sales & Design',
                    'Apre Proses Geliştirme ve İyileştirme',
                                   'Dış Ticaret & Lojistik',
                              'İplik ve Dokuma İşletmeleri',
                                     'Yatırımcı İlişkileri',
                                       'Çalışma İlişkileri',
                                          'Bakım ve Enerji',
                               'Tekstil İşçileri Sendikası',
                                              'Kazan Klima',
                                'Strateji ve İş Geliştirme',
                                   'Bobin Boya İşletmeleri',
                                           'Satış  / Sales',
                                    'Satınalma ve Lojistik',
                                 'Mekanik Atölye ve İmalat',
                                         'Süreç Geliştirme']
Length: 94, dtype: str